### ISSUE TITLE
Index for all pointcut expressions in the project

### ISSUE THREAD

**Issue by lisachenko** [goaop/idea-plugin#3]
I'm looking for the way to collect all injected pointcut expressions from all files into one single index. Here is an example with injected pointcut expression into the Doctrine annotation:

![inheritance-php](https://cloud.githubusercontent.com/assets/640114/7863617/05423766-0566-11e5-9359-7245f07e2b41.png)

There should be an utility class with index of all registered pointcuts in the project. Unfortunately, I can't use the following snippet, because all files are injected fragments:

``` java
Collection<VirtualFile> virtualFiles = FileBasedIndex.getInstance().getContainingFiles(
      FileTypeIndex.NAME,
      GoAopFileType.INSTANCE,
      GlobalSearchScope.allScope(project));

// virtualFiles is always empty
```

How can I get the list of all virtual files with `GoAopFileType.INSTANCE`?

There is `InjectedLanguageManager.getInstance(project).getInjectedPsiFiles(element)` method that looks good, but it requires passing a concrete host element and additional analysis of file type instance, which is not a nice way.

Final destination is `PointcutExpressionUtil.getAllPointcuts()` that can be used later for analysis.

**Comment by lisachenko** [comment]
Question on the devnet-forum: https://devnet.jetbrains.com/message/5544433#5544514

**Comment by lisachenko** [comment]
Ping guru of PhpStorm/IDEA plugins: @Haehnchen @YannCebron @neuro159 @bulenkov

**Comment by Haehnchen** [comment]
guru? :thumbsup:
you should build an custom indexer which filters your files with the expression. basicly i do this for  `@Routes` annotation, too. you are then able to get files by `AnnotationRoutesStubIndex:KEY` see: https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/AnnotationRoutesStubIndex.java

feel free to ask, if u need some more help.

**Comment by lisachenko** [comment]
@Haehnchen thank you for pointing the right direction! I'm really newbie in Java and IDEA internals  Looking into your code...

**Comment by lisachenko** [comment]
@Haehnchen looks good ) Now I have an index with all annotated pointcuts - this is very good step towards to working solution.

However, I'm thinking about the fact why almost every implementation of data indexer uses `FileBasedIndexExtension<String, Void>` to store only important names in the index and then custom code searches for the files by this keys and performs additional processing/matching/etc.

So I have a new questions (sorry, if I boring you):
- Can I create a custom serializable value that will represent matcher for `PhpNamedElement` and store it in the index directly, like `FileBaseIndexExtension<String, PointcutAdvisor>`?
- My indexer can't look into the PSI structure with my custom language implementation inside doctrine annotation. Should I try to use it on the indexer level, or it will be better to store the place with pointcut expression in the index and then just analyse it in the util class
- I also noticed, that after changes in the docBlock part of file, a new record with expression is stored in the cache, but expression can be absolutely invalid for my pointcut query language. Is it possible to check that injected language syntax for docBlock node is valid syntax? How to remove stale records from the cache (I can see my stale versions of pointcut expressions during the process of active changes in the expression itself)

**Comment by Haehnchen** [comment]
iam thankful for every guy that knows more about plugin programming. i welcome every smart people that will able to help on the other plugins, at some time :) 
- Yes customer `DataExternalizer` are possible:
  https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/YamlTranslationStubIndex.java#L160
  https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ServicesDefinitionStubIndex.java#L155
- Indexes are just text structs with limited document structure. Iam also just use them to pre-filter files and in later context iam search for the `values`. this is the nature of this fileindex :)
- whenever a file is changed internal or external a new fileindexer will start, which removes every indexed value of this particular file. so if docBlock switched to invalid just index them.

**Comment by lisachenko** [comment]
@Haehnchen I'm very thankful to you for helping me with my questions! I wish I could help you later, when my knowledge of IDES internals will be good, because now I'm only searching an answers for my questions.

It's pity that devnet forum of IDEA can't give me an answers ( So, looks like you are the only real guy who know how to do plugins and what is more important - you are only one who help me.

I think that I should try to spend more time on looking into your code and try to do this work myself, without extra questions for you. Of course, it's a hard way for me, but I really want to have a working support for aspect-oriented programming in PHP with IDE assistance, this can be a game changer ) 

I'm very carefully read you previous answer and now I understand more about indexes and how to use them. Thanks a lot!

**Comment by YannCebron** [comment]
Please point out where existing documentation is not clear or could be improved: http://www.jetbrains.org/intellij/sdk/docs/basics/indexing_and_psi_stubs.html We welcome any pull requests :)

**Comment by neuro159** [comment]
Sorry gents I'm on vacation and looking through mail only occasionally. 

There is an important aspect you missing here,   that is Stub PSI trees vs normal fully materialised PSI tree and StubElement indexes

That is the key to performance and what powers PhpIndex in php open API

**Comment by lisachenko** [comment]
@YannCebron, @neuro159 Hello guys, I'm very glad to see you there! )) 

@YannCebron I think that I missing a part of documentation with indexing the data from injected languages PSI. 

Case is following: I have a file (PHP) with specific doctrine annotations and my injected syntax into annotations. If I want to index this, then I can build a file indexer that can extract raw phpDoc blocks as string, but then I should reparse the content for my injected block from the index, which is not good. I looked at stub indexer, but looks like I can't access PSI structure for elements, injected into parent PSI element host.

Could you point me in the right direction: is it ok to do a php file indexer and then scan each file for a raw doc-blocks with one more parsing of content in the realtime, or there is a possibility to write a stub-indexer for injected language fragments and PSI items in it?

**Comment by lisachenko** [comment]
@neuro159 could I also ask you to help me select the right way, please? If you can describe your own vision about how this plugin could be implemented internally with description of parsing/indexing/checking pointcuts expressions for PhpNamedElement-s - this will be superb!

For the reference, there is a task #1, that I want to implement for phpStorm. I just want to be sure, that my implementation way won't be wrong and this tool will be fast enough, assuming that one advice can reference all the methods in all classes - this check should be really fast and this is only possible with correct implementation of cache and re-indexing.

Your vision is highly appreciated!

**Comment by lisachenko** [comment]
Alexey, @neuro159 could I ask you to help me please with the question about how should I create an index for injected language fragments (see my previous comment for details)?

I can make it working with real .goaop files, but not for injected fragments and virtual files. What I want is to quickly get all of PointcutExpression PSI elements in all php files, but I can't find the right way to implement this. Am I missing something?

**Comment by lisachenko** [comment]
it's pity, but I don't know how to do this in my plugin ( 

Guys, could you help me with simple working example? I want to make aspect-oriented programming so easy with PhpStorm, but my knowledge of IDEA internals and Java is not so good. Just show me the way or single working example, how to work with injected fragments PSI to match PHP elements (classes, methods, properties) against regular expression.

I'm also ready to pay someone for that. Kindly ask you guys to help me, want to bring this project to life with PHP7 support and AOP )

@neuro159 could you help me with my issue/plugin? This should be a killer-feature and can change developers mind to use AOP in projects.
